# This file is part of ICU4X. For terms of use, please see the file
# called LICENSE at the top level of the ICU4X source tree
# (online at: https://github.com/unicode-org/icu4x/blob/main/LICENSE ).

# This is a cargo-make file included in the toplevel Makefile.toml

[tasks.testdata-download-sources]
description = "Download fresh CLDR JSON, overwriting the existing CLDR JSON."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-testdata-download-sources",
    "--features=bin",
    "--",
    "-v",
]

[tasks.icu4x-key-extract]
description = "Extracts ICU4X resource keys used by a binary."
category = "ICU4X Data"
script_runner = "bash"
script = '''strings ${1} | grep -e "icu4x_key_tag\w" | sed s/icu4x_key_tag// | sort > ${2}'''

[tasks.testdata-fingerprint-blob]
description = "Generate a fingerprint for the ICU4X testdata.postcard file."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-fingerprint-data",
    "--features=experimental,bin",
    "--",
    "--format=blob",
    "--data=provider/testdata/data/testdata.postcard",
    "--out=provider/testdata/data/blob.fingerprint",
]

[tasks.testdata-fingerprint-json]
description = "Generate a fingerprint for the ICU4X JSON testdata file."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-fingerprint-data",
    "--features=experimental,bin",
    "--",
    "--format=dir",
    "--data=provider/testdata/data/json",
    "--out=provider/testdata/data/json.fingerprint",
]

[tasks.testdata-fingerprint]
description = "Generate a fingerprint for Postcard and JSON testdata."
category = "ICU4X Data"
dependencies = [
    "testdata-fingerprint-json",
    "testdata-fingerprint-blob",
]



[tasks.testdata-build-hello-world]
description = "Build the Hello World postcard testdata file."
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-datagen",
    "--features=experimental,bin",
    "--",
    "--format=blob",
    "--hello-world-key",
    "--all-locales",
    "--out=provider/blob/tests/data/hello_world.postcard",
    "--overwrite",
]

[tasks.testdata]
description = "Rebuild all ICU4X testdata from source data checked into the repository"
category = "ICU4X Data"
command = "cargo"
args = [
    "run",
    "--bin=icu4x-testdata-datagen",
    "--features=bin",
]

[tasks.testdata-check-unchanged]
description = "Rebuild ICU4X testdata and ensure that the working copy is clean"
category = "ICU4X Data"
dependencies = [
    "testdata"
]
script_runner = "@duckscript"
script = '''
exit_on_error true

output = exec git status --porcelain=v1 provider/testdata/data
output_length = length ${output.stdout}
if greater_than ${output_length} 0
    msg = array "" ""
    array_push ${msg} "Test data needs to be updated. Please run `cargo make testdata`:"
    array_push ${msg} ""
    array_push ${msg} "${output.stdout}"
    msg = array_join ${msg} "\n"
    trigger_error ${msg}
end
'''

[tasks.testdata-check]
description = "Rebuild ICU4X testdata and perform various checks pertaining to it"
category = "ICU4X Data"
dependencies = [
    "testdata-check-unchanged",
]
