// generated by diplomat-tool
import type { CalendarKind } from "./CalendarKind"
import type { pointer, codepoint } from "./diplomat-runtime.d.ts";



/**
 * See the [Rust documentation for `MismatchedCalendarError`](https://docs.rs/icu/latest/icu/datetime/struct.MismatchedCalendarError.html) for more information.
 */
export class DateTimeMismatchedCalendarError {
    get thisKind(): CalendarKind;
    get dateKind(): CalendarKind | null;
    /** @internal */
    constructor();

}